### ISSUE TITLE
JQuery 3?

### ISSUE THREAD

**Issue by thingswelike** [FeliciousX/jquery-tiles-gallery#1]
Love this layout and surprisingly it's still unique among grid layouts (just spent all day looking for a replacement).
Any chance of a JQuery 3 version?
Another nice-to-have feature for responsive layouts would be a method of having the height either set in css, or have break points settable in the JQuery.

**Comment by FeliciousX** [comment]
whoops, hi @thingswelike 

I created this repo a long time ago because I needed the library to be available in `bower` . It's available online by GreenTreeLabs but it wasn't in any package manager ( 2013 was a long time ago, `npm` wasn't there yet?)

I need to somehow deprecate this repo. 

So to answer your question, no chance of a JQuery version 3 unless they publish it again. I couldn't find the source anymore :(

**Comment by thingswelike** [comment]
Ah I see - thanks for the response!
